rails:
  build: ./rails
  links:
    - "mysql"
  ports:
    - "3000:3000"
mysql:
  build: ./mysql
  expose:
    - "3306"
  environment
  	MYSQL_DATABASE: webspider_development
  	MYSQL_ROOT_PASSWORD: 831124
  volumes:
  	- ./data/mysql:/var/lib/mysql