rails:
  build: ./rails
  container_name: rails
  links:
    - "mysql"
  ports:
    - "3000:3000"
  
  #environment:
  #  - DATABASE_URL=mysql://mysql:34387
  volumes:
    # 挂载源代码目录
    - ./code/Web-Spider:/usr/src/app/
  command: "bash /tmp/build.sh"
mysql:
  build: ./mysql
  container_name: mysql
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: 831124
  volumes:
    - ./data/mysql:/var/lib/mysql