FROM ruby:2.3

ADD ../code/Web-Spider /usr/src/app/
# ADD build.sh /usr/src/app/Web-Spider/
WORKDIR /usr/src/app/Web-Spider

RUN bundle install
RUN bundle exec rake db:create
RUN bundler exec rake db:migrate

EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]