FROM rails:latest

# 拷贝部署脚本到镜像
ADD build.sh /tmp/
# 允许挂载源码目录
VOLUME /usr/src/app/

WORKDIR /usr/src/app

#RUN echo `pwd` 

#RUN bundle install

EXPOSE 3000
#CMD ["rails", "server", "-b", "0.0.0.0"]